import type { Metadata } from "next";
import { ArrowRight, CheckCircle2, FlaskConical, Scale, ShieldCheck } from "lucide-react";
import { PageBreadcrumbs } from "@/components/layout/page-breadcrumbs";
import { Badge } from "@/components/ui/badge";
import { FoodsLink } from "@/components/pages/foods-link";
import { PulseSpecBuilder } from "@/features/catalog/components/pulse-spec-builder";
import { pulseBaseline, pulseFamilies, pulseForms, pulseSources } from "@/features/catalog/data/pulse-knowledge";
import { absoluteUrl } from "@/config/site";

export const metadata: Metadata = { title: "Pulses & Lentils: Identities, Forms and Specifications", description: "Compare pulse species and trade names, understand whole, split and flour forms, and build a source-backed pulse RFQ.", alternates: { canonical: absoluteUrl("/knowledge/pulses") } };

export default function PulseKnowledgePage() {
  return <>
    <section className="border-b border-border bg-background"><div className="container-shell py-6"><PageBreadcrumbs /></div></section>
    <section className="bg-hero-wash py-16 sm:py-20"><div className="container-shell grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="section-kicker">Pulses & lentils knowledge centre</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-0.05em] sm:text-6xl">Match the trade name to the pulse. Then specify the form and lot.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">A pulse identity, its market class, its processing form and its commercial grade are different attributes. This guide separates them so buyers can compare like with like.</p></div><div className="rounded-2xl border border-primary/15 bg-card p-6"><ShieldCheck className="size-7 text-primary" /><p className="mt-5 font-semibold">Evidence boundary</p><p className="mt-2 text-sm leading-6 text-muted-foreground">The table is an FSSAI reference baseline—not a batch COA or export-destination guarantee. Exact crop, origin, treatment, limits and testing are confirmed in the RFQ.</p></div></div></section>
    <section className="section-space bg-background"><div className="container-shell"><p className="section-kicker">Identity map</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Different names may point to the same crop family.</h2><div className="mt-9 grid gap-5 lg:grid-cols-2">{pulseFamilies.map((family) => <article key={family.key} className="rounded-2xl border border-border bg-card p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-2xl font-semibold">{family.name}</h3><p className="mt-1 text-sm italic text-muted-foreground">{family.scientificName}</p></div><Badge variant="outline">Identity mapped</Badge></div><p className="mt-5 text-sm"><strong>Trade names:</strong> {family.tradeNames}</p><p className="mt-4 leading-7 text-muted-foreground">{family.distinction}</p></article>)}</div></div></section>
    <section className="section-space bg-brand-surface"><div className="container-shell"><div className="grid gap-5 md:grid-cols-3">{pulseForms.map((form) => <article key={form.key} className="rounded-2xl bg-card p-7 shadow-sm"><FlaskConical className="size-6 text-primary" /><h2 className="mt-5 text-2xl font-semibold">{form.label}</h2><p className="mt-4 leading-7 text-muted-foreground">{form.meaning}</p></article>)}</div><div className="mt-10 overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-6"><p className="section-kicker">FSSAI reference baseline</p><h2 className="mt-3 text-2xl font-semibold">Whole versus pulses without seed coat</h2><p className="mt-2 text-sm text-muted-foreground">Confirm the current regulation and destination rules at contract time.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-primary/5"><tr><th className="p-4">Parameter</th><th className="p-4">With seed coat</th><th className="p-4">Without seed coat</th></tr></thead><tbody>{pulseBaseline.map((row) => <tr key={row.parameter} className="border-t border-border"><th className="p-4 font-semibold">{row.parameter}</th><td className="p-4">{row.withSeedCoat}</td><td className="p-4">{row.withoutSeedCoat}</td></tr>)}</tbody></table></div></div></div></section>
    <section className="section-space bg-background"><div className="container-shell"><PulseSpecBuilder /><div className="mt-10 grid gap-5 md:grid-cols-3">{[[Scale,"Contract the lot","Declare family, market class, form, size/count, colour, crop, origin, defects, treatment and packing."],[FlaskConical,"Request batch evidence","Align physical, contaminant, residue and microbiological tests with product form and destination."],[CheckCircle2,"Keep claims honest","‘Premium’ and ‘export standard’ are not substitutes for measurable limits or a lot-specific COA."]].map(([Icon,title,text]) => <article key={title as string} className="rounded-2xl border border-border p-6"><Icon className="size-6 text-primary" /><h2 className="mt-5 text-xl font-semibold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{text as string}</p></article>)}</div></div></section>
    <section className="section-space bg-brand-ink text-white"><div className="container-shell"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-gold">Primary sources</p><div className="mt-6 grid gap-3">{pulseSources.map((source) => <a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-4 rounded-xl border border-white/15 p-4 text-sm text-white/80 hover:border-brand-gold"><span><strong className="text-white">{source.authority}</strong> — {source.title}</span><ArrowRight className="size-4 shrink-0" /></a>)}</div><FoodsLink href="/catalog?category=Pulses+%26+Lentils" className="mt-8 inline-flex font-bold text-brand-gold">Browse pulse catalogue →</FoodsLink></div></section>
  </>;
}
