import type { Metadata } from "next";
import { ArrowRight, CheckCircle2, FlaskConical, ShieldCheck } from "lucide-react";
import { PageBreadcrumbs } from "@/components/layout/page-breadcrumbs";
import { Badge } from "@/components/ui/badge";
import { FoodsLink } from "@/components/pages/foods-link";
import { SpiceSpecBuilder } from "@/features/catalog/components/spice-spec-builder";
import { spiceGroups, spiceIdentities, spiceRiskControls, spiceSources } from "@/features/catalog/data/spice-knowledge";
import { absoluteUrl } from "@/config/site";

export const metadata: Metadata = { title: "Spices & Herbs: Identity, Quality and Safety Specifications", description: "Compare spice identities and forms, understand quality and safety parameters, and build a source-backed spice RFQ.", alternates: { canonical: absoluteUrl("/knowledge/spices") } };

export default function SpiceKnowledgePage() { return <>
  <section className="border-b border-border bg-background"><div className="container-shell py-6"><PageBreadcrumbs /></div></section>
  <section className="bg-hero-wash py-16 sm:py-20"><div className="container-shell grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="section-kicker">Spices & herbs knowledge centre</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-0.05em] sm:text-6xl">Botanical identity first. Measurable flavour and safety next.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Whole, crushed and ground spices cannot share one generic quality promise. This guide separates identity, plant part, processing form, sensory strength, cleanliness, treatment and destination safety requirements.</p></div><div className="rounded-2xl border border-primary/15 bg-card p-6"><ShieldCheck className="size-7 text-primary" /><p className="mt-5 font-semibold">No automatic “export grade”</p><p className="mt-2 text-sm leading-6 text-muted-foreground">FSSAI is the Indian product baseline. Import-market limits and buyer specifications can differ; a lot-specific COA and treatment evidence remain necessary.</p></div></div></section>
  <section className="section-space bg-background"><div className="container-shell"><p className="section-kicker">Catalogue architecture</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Four product types need four approval paths.</h2><div className="mt-9 grid gap-5 md:grid-cols-2">{spiceGroups.map((group) => <article key={group.key} className="rounded-2xl border border-border bg-card p-7"><Badge variant="outline">{group.name}</Badge><p className="mt-5 text-sm"><strong>Examples:</strong> {group.examples}</p><p className="mt-4 leading-7 text-muted-foreground">{group.rule}</p></article>)}</div></div></section>
  <section className="section-space bg-brand-surface"><div className="container-shell"><p className="section-kicker">Identity comparison</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">High-value distinctions buyers should see.</h2><div className="mt-9 grid gap-5 lg:grid-cols-2">{spiceIdentities.map((item) => <article key={item.key} className="rounded-2xl bg-card p-7 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-2xl font-semibold">{item.name}</h3><p className="mt-1 text-sm italic text-muted-foreground">{item.scientificName}</p></div><Badge variant="outline">{item.aliases}</Badge></div><p className="mt-5 leading-7 text-muted-foreground">{item.discriminator}</p><div className="mt-5 rounded-xl bg-primary/5 p-4 text-sm leading-6"><strong>Contract parameters:</strong> {item.contract}</div></article>)}</div></div></section>
  <section className="section-space bg-background"><div className="container-shell"><SpiceSpecBuilder /><div className="mt-10 overflow-hidden rounded-2xl border border-border"><div className="border-b border-border bg-card p-6"><p className="section-kicker">Risk-control matrix</p><h2 className="mt-3 text-2xl font-semibold">Evidence belongs to the selected lot and destination.</h2></div><div className="divide-y divide-border">{spiceRiskControls.map((row) => <div key={row.risk} className="grid gap-2 bg-card p-5 md:grid-cols-[14rem_1fr]"><strong>{row.risk}</strong><span className="text-sm leading-6 text-muted-foreground">{row.controls}</span></div>)}</div></div><div className="mt-8 rounded-2xl border border-amber-400/30 bg-amber-50 p-6 text-amber-950"><CheckCircle2 className="size-6" /><h2 className="mt-4 text-xl font-semibold">Vegan blend gate</h2><p className="mt-2 text-sm leading-6">Every masala or seasoning blend stays formulation-dependent until its complete formula, carriers, flavours, additives, processing aids, allergens and cross-contact statement are reviewed. Dairy, egg, meat or marine derivatives are prohibited; honey must be disclosed as the sole permitted exception and cannot be labelled vegan.</p></div></div></section>
  <section className="section-space bg-brand-ink text-white"><div className="container-shell"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-gold">Primary sources</p><div className="mt-6 grid gap-3">{spiceSources.map((source) => <a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-4 rounded-xl border border-white/15 p-4 text-sm text-white/80 hover:border-brand-gold"><span><strong className="text-white">{source.authority}</strong> — {source.title}</span><ArrowRight className="size-4 shrink-0" /></a>)}</div><FoodsLink href="/catalog?category=Spices+%26+Herbs" className="mt-8 inline-flex font-bold text-brand-gold">Browse spice catalogue →</FoodsLink></div></section>
 </>; }
