"use client";
import type { CSSProperties, ReactNode } from "react";
import { cn } from "@/lib/utils";
import { H_MARK_PATH, type LogoSizeKey, type LogoVariant, resolveSize } from "./brand";

const ID = { descriptor: "Foods", ink: "#132F2A", accent: "#2E6B55", signal: "#6E9C62", light: "#FCF9F2", dark: "#0A1815", divider: "#DBE4D9" } as const;
export const HMark = ({ color, size }: { color: string; size: number }) => <svg viewBox="0 0 852 833" width={size} height={Math.round(size * 833 / 852)} aria-hidden focusable="false" style={{ display: "block", flexShrink: 0 }}><path fillRule="evenodd" fill={color} d={H_MARK_PATH} /></svg>;

export interface WordmarkProps { nameColor: string; accentColor?: string; venturesColor?: string; descriptorColor?: string; nameSize: number; showDescriptor?: boolean; align?: "left" | "center"; compact?: boolean; descriptor?: string }
export const Wordmark = ({ nameColor, descriptorColor, venturesColor, accentColor, nameSize, showDescriptor = true, align = "left", descriptor = ID.descriptor }: WordmarkProps) => <div role="img" aria-label={`Harobal ${descriptor}`} style={{ display: "flex", flexDirection: "column", alignItems: align === "center" ? "center" : "flex-start", lineHeight: 1 }}><span style={{ color: nameColor, fontFamily: "var(--font-outfit), var(--font-sans), sans-serif", fontSize: nameSize, fontWeight: 650, letterSpacing: ".18em", whiteSpace: "nowrap" }}>HAROBAL</span>{showDescriptor && <span style={{ color: descriptorColor ?? venturesColor ?? accentColor ?? ID.accent, fontFamily: "var(--font-outfit), var(--font-sans), sans-serif", fontSize: Math.max(10, Math.round(nameSize * .64)), fontWeight: 600, letterSpacing: ".2em", marginTop: Math.max(4, Math.round(nameSize * .24)), textTransform: "uppercase", whiteSpace: "nowrap" }}>{descriptor}</span>}</div>;

export interface IconContainerProps { children: ReactNode; shape: "square" | "circle" | "none"; bgColor: string; ringColor?: string; ringWidth?: number; size: number }
export const IconWrap = ({ children, shape, bgColor, ringColor, ringWidth = 2, size }: IconContainerProps) => <span style={{ alignItems: "center", backgroundColor: shape === "none" ? "transparent" : bgColor, borderRadius: shape === "circle" ? "50%" : shape === "square" ? `${Math.round(size * .18)}px` : 0, boxShadow: ringColor ? `0 0 0 ${ringWidth}px ${ringColor}` : undefined, boxSizing: "border-box", display: "inline-flex", height: size, justifyContent: "center", padding: shape === "none" ? 0 : Math.round(size * .16), width: size }}>{children}</span>;

export interface HarobalLogoProps { variant?: LogoVariant; size?: LogoSizeKey | number; showDescriptor?: boolean; className?: string; style?: CSSProperties; label?: string; descriptor?: string }
const HarobalLogo = ({ variant = "primary", size = "lg", showDescriptor = true, className, style, label = "Harobal Foods", descriptor = ID.descriptor }: HarobalLogoProps) => {
  const { symbolWidth, nameSize } = resolveSize(size); const dark = variant === "dark" || variant === "dark-horizontal" || variant === "wordmark-dark" || variant === "mono-white"; const monochrome = variant.startsWith("mono-"); const icon = variant.startsWith("icon-") || variant.startsWith("app-") || variant.startsWith("favicon"); const wordmarkOnly = variant.startsWith("wordmark"); const stacked = variant === "primary" || variant === "compact" || variant === "alternate-stacked" || variant === "dark";
  const markColor = monochrome ? (variant === "mono-white" ? ID.light : variant === "mono-black" ? "#000000" : ID.accent) : dark ? ID.light : ID.accent; const nameColor = dark ? ID.light : ID.ink; const supportColor = dark ? ID.signal : ID.accent;
  if (icon) { const circle = variant === "icon-circle" || variant === "app-circle"; const contained = circle || variant === "icon-square" || variant === "icon-light" || variant === "app-square" || variant === "app-light" || variant === "favicon"; const s = typeof size === "number" ? size : symbolWidth; const reverse = dark || variant === "app-square" || variant === "favicon"; return <span className={cn("inline-flex", className)} style={style} role="img" aria-label={label}><IconWrap shape={contained ? (circle ? "circle" : "square") : "none"} bgColor={reverse ? ID.dark : ID.light} ringColor={circle ? ID.accent : undefined} size={s}><HMark color={reverse ? ID.light : ID.accent} size={contained ? Math.round(s * .64) : s} /></IconWrap></span>; }
  const wordmark = <Wordmark nameColor={nameColor} descriptorColor={supportColor} nameSize={nameSize} showDescriptor={showDescriptor} descriptor={descriptor} />; if (wordmarkOnly) return <span className={cn("inline-flex", className)} style={style}>{wordmark}</span>;
  return <span className={cn("inline-flex", stacked ? "flex-col items-center" : "items-center", className)} style={{ gap: stacked ? Math.max(8, symbolWidth * .14) : Math.max(10, symbolWidth * .24), ...style }} role="img" aria-label={label}><HMark color={markColor} size={symbolWidth} />{!stacked && <span aria-hidden style={{ alignSelf: "stretch", background: dark ? "rgba(255,255,255,.28)" : ID.divider, minHeight: Math.round(symbolWidth * .58), width: 1 }} />}{wordmark}</span>;
};
export default HarobalLogo;
