import type { Metadata } from "next";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { PageBreadcrumbs } from "@/components/layout/page-breadcrumbs";
import { Badge } from "@/components/ui/badge";
import { FoodsLink } from "@/components/pages/foods-link";
import { NutSpecBuilder } from "@/features/catalog/components/nut-spec-builder";
import { nutIdentities, nutRiskControls, nutSources, nutStyles } from "@/features/catalog/data/nuts-knowledge";
import { absoluteUrl } from "@/config/site";

export const metadata: Metadata = { title: "Nuts & Dried Fruits: Identities, Styles and Quality", description: "Compare nut and dried-fruit identities, kernel styles, treatments, defect parameters and lot-specific safety requirements.", alternates: { canonical: absoluteUrl("/knowledge/nuts-dried-fruits") } };

export default function NutsKnowledgePage() { return <>
  <section className="border-b border-border bg-background"><div className="container-shell py-6"><PageBreadcrumbs /></div></section>
  <section className="bg-hero-wash py-16 sm:py-20"><div className="container-shell grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="section-kicker">Nuts & dried fruits knowledge centre</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-0.05em] sm:text-6xl">Identity, kernel style and size are separate buying decisions.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">A truthful specification distinguishes the plant product, shell or pit status, whole/piece style, count method, treatment, defects and lot-specific food-safety evidence.</p></div><div className="rounded-2xl border border-primary/15 bg-card p-6"><ShieldCheck className="size-7 text-primary"/><p className="mt-5 font-semibold">Programme is not proof</p><p className="mt-2 text-sm leading-6 text-muted-foreground">“Aflatoxin-control programme” describes an intended control system. Only representative sampling and a lot-linked result support compliance for a shipment.</p></div></div></section>
  <section className="section-space bg-background"><div className="container-shell"><p className="section-kicker">Product identities</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Compare the product before comparing its grade.</h2><div className="mt-9 grid gap-5 lg:grid-cols-2">{nutIdentities.map((item)=><article key={item.key} className="rounded-2xl border border-border bg-card p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-2xl font-semibold">{item.name}</h3><p className="mt-1 text-sm italic text-muted-foreground">{item.scientificName}</p></div><Badge variant="outline">Plant-based</Badge></div><p className="mt-5 leading-7 text-muted-foreground">{item.distinction}</p><div className="mt-5 rounded-xl bg-primary/5 p-4 text-sm leading-6"><strong>Contract parameters:</strong> {item.parameters}</div></article>)}</div></div></section>
  <section className="section-space bg-brand-surface"><div className="container-shell"><div className="grid gap-5 md:grid-cols-3">{nutStyles.map((style)=><article key={style.key} className="rounded-2xl bg-card p-7 shadow-sm"><h2 className="text-2xl font-semibold">{style.label}</h2><p className="mt-4 leading-7 text-muted-foreground">{style.meaning}</p></article>)}</div><div className="mt-10 overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-6"><p className="section-kicker">Lot evidence</p><h2 className="mt-3 text-2xl font-semibold">Quality and safety controls change by identity.</h2></div><div className="divide-y divide-border">{nutRiskControls.map((row)=><div key={row.risk} className="grid gap-2 p-5 md:grid-cols-[14rem_1fr]"><strong>{row.risk}</strong><span className="text-sm leading-6 text-muted-foreground">{row.control}</span></div>)}</div></div></div></section>
  <section className="section-space bg-background"><div className="container-shell"><NutSpecBuilder/><div className="mt-8 rounded-2xl border border-amber-400/30 bg-amber-50 p-6 text-sm leading-6 text-amber-950"><strong>Plant-based formulation gate:</strong> plain nuts and dried fruits are eligible. Flavoured, glazed or coated programs require ingredient, additive, allergen and cross-contact review. Dairy, egg, meat and marine ingredients remain prohibited; honey must be explicitly disclosed and cannot be labelled vegan.</div></div></section>
  <section className="section-space bg-brand-ink text-white"><div className="container-shell"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-gold">Primary sources</p><div className="mt-6 grid gap-3">{nutSources.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-4 rounded-xl border border-white/15 p-4 text-sm text-white/80 hover:border-brand-gold"><span><strong className="text-white">{source.authority}</strong> — {source.title}</span><ArrowRight className="size-4 shrink-0"/></a>)}</div><FoodsLink href="/catalog?category=Nuts+%26+Dry+Fruits" className="mt-8 inline-flex font-bold text-brand-gold">Browse catalogue →</FoodsLink></div></section>
 </>; }
